"""Sub-agent HARD_STOP instruction templates for each pipeline stage.

These templates are embedded in ``get_pipeline_status`` responses so that the
orchestrator knows how to dispatch sub-agents.  Placeholders like ``{run_id}``
are filled at runtime by ``status.py``.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Stage 1 — User Input
# ---------------------------------------------------------------------------

STAGE_1_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 1 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(stage='input_report') BEFORE spawning the sub-agent.\n"
    "(No run_id yet — Stage 1 creates it via submit_input_report.)\n\n"
    "Sub-agent tools: get_pipeline_status, submit_input_report\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, extract the run_id from its output, "
    "then call complete_stage(run_id='<run_id_from_submit>'), "
    "then call get_pipeline_status.\n"
    "If Stage 1 is not complete, re-dispatch the sub-agent. Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# ---------------------------------------------------------------------------
# Stage 2 — Data Validation
# ---------------------------------------------------------------------------

STAGE_2_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 2 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='data_validation') "
    "BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, validate_dataset, "
    "detect_and_parse_dataset, transform_dataset, save_routing_context, "
    "stratified_split_tool, save_proposed_mapping\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 2 is not complete:\n"
    "  - Check the status detail field. If detail is 'mapping_confirmation_needed', read the\n"
    "    file at outputs/{run_id}/validation/proposed_mapping.json. Present the proposed\n"
    "    field mapping as a table to the user (source field → target field), include a few\n"
    "    sample rows for context, and list any unmapped fields. Ask the user to confirm the\n"
    "    mapping or provide corrections.\n"
    "    You MUST wait for the user's actual reply. Do NOT assume, guess, or auto-confirm.\n"
    "    Then call start_stage(run_id='{run_id}', stage='data_validation') again to re-activate\n"
    "    the stage scope, and re-dispatch the sub-agent with the confirmed (or corrected)\n"
    "    mapping in the conversation context. (Skipping start_stage will spawn the sub-agent\n"
    "    with orchestrator-scope tools and stage tools will be invisible.)\n"
    "  - If detail is 'data_quality_critical_fail', read the failing schema_findings from\n"
    "    outputs/{run_id}/validation/data_quality_report.json (those with severity='critical'\n"
    "    and status='fail'). Present the violations to the user and ask for a corrected field\n"
    "    mapping. Do NOT proceed to downstream stages — they would silently produce broken\n"
    "    metrics on misaligned data. After collecting the corrected mapping, call\n"
    "    start_stage(run_id='{run_id}', stage='data_validation') again and re-dispatch the\n"
    "    sub-agent with the corrected mapping in context.\n"
    "  - Otherwise, call start_stage(run_id='{run_id}', stage='data_validation') again, then\n"
    "    re-dispatch the sub-agent. Do not call stage tools yourself.\n"
    "  - If Stage 2 remains incomplete after 2 re-dispatches, report the error to the\n"
    "    user and halt.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# ---------------------------------------------------------------------------
# Stage 3 — Backend Setup
# ---------------------------------------------------------------------------

STAGE_3_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT perform backend setup from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='backend_setup') "
    "BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_default_pricing, save_backend_options\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 3 is not complete:\n"
    "  - Check the status detail field.\n"
    "  - If detail is 'backend_selection_needed', read the file at\n"
    "    outputs/{run_id}/backend_options.json. Present the available backends to the user.\n"
    "    If backends exist: ask 'Choose one of these existing backends, or create a new one.'\n"
    "    If no backends: ask 'No backends configured. Please provide: label, provider,\n"
    "    model, requests_per_minute, and tokens_per_minute.'\n"
    "    If the user chooses to create a new backend, collect: label, provider, model,\n"
    "    requests_per_minute, and tokens_per_minute.\n"
    "    You MUST wait for the user's actual reply. Do NOT assume, guess, or fabricate\n"
    "    the user's backend choice or configuration values.\n"
    "    Then call start_stage(run_id='{run_id}', stage='backend_setup') again to re-activate\n"
    "    the stage scope, and re-dispatch the sub-agent with the user's selection or config\n"
    "    in the conversation context. (Skipping start_stage will spawn the sub-agent with\n"
    "    orchestrator-scope tools and stage tools will be invisible.)\n"
    "  - If detail is 'pricing_missing', ask the user for input_cost_per_million_tokens,\n"
    "    cached_cost_per_million_tokens, and output_cost_per_million_tokens.\n"
    "    You MUST wait for the user's actual reply. Do NOT assume, guess, or fabricate values.\n"
    "    Then call start_stage(run_id='{run_id}', stage='backend_setup') again, and\n"
    "    re-dispatch the sub-agent with these pricing values in the conversation context.\n"
    "  - Otherwise, call start_stage(run_id='{run_id}', stage='backend_setup') again, then\n"
    "    re-dispatch the sub-agent. Do not perform backend setup yourself.\n"
    "  - If Stage 3 remains incomplete after 3 re-dispatches, report the error to the\n"
    "    user and halt.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# ---------------------------------------------------------------------------
# Stage 4 — Refinement Loop (dynamic phases)
# ---------------------------------------------------------------------------

STAGE_4_COLD_START_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='review_cold') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "build_review_briefing_tool, record_directive_outcomes_tool\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_BUILD_V1_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 build-phase tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='prompt_building') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, get_routing_context_tool, "
    "get_child_variants_tool, get_edit_directives_tool, get_prompt_text_tool, get_score_report_tool, "
    "init_search_state_tool, register_candidate_tool, record_eval_result_tool, "
    "advance_step_tool, save_prompt_tool, run_eval\n"
    "Your tools: get_pipeline_status only\n\n"
    "NOTE: optimize_routing_prompt is the pipeline entry-point tool (orchestrator-level only). "
    "Do not call it from within the sub-agent.\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_BUILD_OPTIMIZE_INSTRUCTION: str = (
    "<DISPATCH_CONTEXT>\n"
    "This is an optimization round (round 2+ in the refinement loop). A search state already exists for this run.\n"
    "- Begin by calling get_search_state_tool (NOT init_search_state_tool).\n"
    "- Skip Phase 1 of your system prompt entirely. Proceed directly to Phase 2.\n"
    "- Calling init_search_state_tool now would clobber the optimization history.\n"
    "</DISPATCH_CONTEXT>\n\n"
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 build-phase tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='prompt_building') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, get_routing_context_tool, "
    "get_child_variants_tool, get_edit_directives_tool, get_prompt_text_tool, get_score_report_tool, "
    "init_search_state_tool, register_candidate_tool, record_eval_result_tool, "
    "advance_step_tool, save_prompt_tool, run_eval\n"
    "Your tools: get_pipeline_status only\n\n"
    "NOTE: optimize_routing_prompt is the pipeline entry-point tool (orchestrator-level only). "
    "Do not call it from within the sub-agent.\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# Backward-compat alias — external callers keep working for one release.
STAGE_4_BUILD_INSTRUCTION = STAGE_4_BUILD_V1_INSTRUCTION

STAGE_4_RERUN_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 build-phase tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='prompt_building') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, get_routing_context_tool, "
    "get_prompt_text_tool, init_search_state_tool, register_candidate_tool, record_eval_result_tool, "
    "advance_step_tool, save_prompt_tool, run_eval\n"
    "Your tools: get_pipeline_status only\n\n"
    "NOTE: This is a rerun — the Prompt Builder Rerun agent will restructure the existing prompt "
    "for the new backend. Source prompt version: '{source_prompt_version}'. "
    "New backend: '{new_backend}'.\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_BUILD_RECOVERING_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 build-phase tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='prompt_building') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, get_routing_context_tool, "
    "get_child_variants_tool, get_edit_directives_tool, get_prompt_text_tool, get_score_report_tool, "
    "init_search_state_tool, register_candidate_tool, record_eval_result_tool, "
    "advance_step_tool, save_prompt_tool, run_eval, run_batch_eval\n"
    "Your tools: get_pipeline_status only\n\n"
    "RECOVERY MODE: active_evals is non-empty. The sub-agent must call "
    "run_batch_eval(run_id='{run_id}', candidates=[]) to resume in-flight evaluations. "
    "Completed evals (eval_status='complete') are recovered from disk automatically; "
    "only missing or incomplete evals (eval_status='pending' or 'running') are re-run.\n\n"
    "NOTE: optimize_routing_prompt is the pipeline entry-point tool (orchestrator-level only). "
    "Do not call it from within the sub-agent.\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# Shared steady-review sub-agent toolbelt — used by both STAGE_4_REVIEW_INSTRUCTION
# and STAGE_4_REVIEW_INSTRUCTION_EMOSA so the two instructions stay in sync.
_STEADY_REVIEW_TOOLS_LINE: str = (
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "build_review_briefing_tool, record_directive_outcomes_tool, "
    "get_prompt_text_tool, query_holdout_examples_tool"
)

STAGE_4_REVIEW_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 review-phase tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='review') BEFORE spawning the sub-agent.\n\n"
    + _STEADY_REVIEW_TOOLS_LINE
    + "\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent. "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_REVIEW_INSTRUCTION_EMOSA: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 review-phase tools from the current context.\n\n"
    "REQUIRED: Spawn {num_trajectories} independent sub-agents IN PARALLEL, one per trajectory.\n"
    "CONTRACT: Iterate trajectory_id in 0..{max_trajectory_id} and dispatch exactly one sub-agent per id "
    "in a single parallel batch. Do NOT split the fanout into nested groups or delegate the loop to another "
    "sub-agent — the orchestrator must dispatch all {num_trajectories} sub-agents directly from one "
    "tool-call batch.\n"
    "Each sub-agent gets the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='review') BEFORE spawning sub-agents.\n\n"
    "Each sub-agent must be told its trajectory_id (0 through {max_trajectory_id}).\n"
    "Include in each sub-agent's conversation context:\n"
    '"Your trajectory_id is <N>. Your run_id is {run_id}."\n\n'
    "Each sub-agent must call record_directive_outcomes_tool(run_id='{run_id}', "
    "trajectory_id=<N>, child_variants=[...]) — server writes "
    "child_variants_t<N>.json instead of single-slot child_variants.json.\n\n" + _STEADY_REVIEW_TOOLS_LINE + "\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: Wait for ALL {num_trajectories} sub-agents (including any still running in "
    "background) to complete BEFORE calling complete_stage. A single sub-agent finishing "
    "does NOT mean review phase is done — you must wait for every trajectory_id in "
    "0..{max_trajectory_id}. If polling with get_pipeline_status, keep waiting while it "
    "reports 'review phase (partial, N/{num_trajectories})'. Only call "
    "complete_stage(run_id='{run_id}') once all {num_trajectories} sub-agents have returned, "
    "then call get_pipeline_status.\n"
    "If Stage 4 is not complete, re-dispatch the appropriate sub-agent(s). "
    "Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_CALIBRATION_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='calibration') BEFORE spawning the sub-agent.\n\n"
    "PRE-DISPATCH CHECK: Before spawning, verify that "
    "outputs/{run_id}/search/build_dispatched.json does not exist. "
    "If it does, a build sub-agent is already in-flight — wait for it to complete.\n\n"
    "CALIBRATION MODE: No trajectories are seeded yet. The sub-agent must:\n"
    "  1. Activate odysseus_review_agent_cold_start to emit K diverse candidate prompts.\n"
    "  2. Call odysseus_prompt_builder to compile and register each candidate.\n"
    "  3. Call run_batch_eval to score all K candidates.\n"
    "  4. Call advance_step_tool to seed K trajectories from scored candidates and flip "
    "loop_phase to 'review'.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "odysseus_review_agent_cold_start, odysseus_prompt_builder, "
    "run_batch_eval, advance_step_tool\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "After K calibration variants are scored, advance_step_tool seeds K trajectories "
    "and flips loop_phase to 'review'. Re-dispatch the appropriate sub-agent for "
    "subsequent phases. Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_CALIBRATION_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='calibration') BEFORE spawning the sub-agent.\n\n"
    "PRE-DISPATCH CHECK: Before spawning, verify that "
    "outputs/{run_id}/search/build_dispatched.json does not exist. "
    "If it does, a build sub-agent is already in-flight — wait for it to complete.\n\n"
    "CALIBRATION MODE: No trajectories are seeded yet. The sub-agent must:\n"
    "  1. Activate odysseus_review_agent_cold_start to emit K diverse candidate prompts.\n"
    "  2. Call odysseus_prompt_builder to compile and register each candidate.\n"
    "  3. Call run_batch_eval to score all K candidates.\n"
    "  4. Call advance_step_tool to seed K trajectories from scored candidates and flip "
    "loop_phase to 'review'.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "odysseus_review_agent_cold_start, odysseus_prompt_builder, "
    "run_batch_eval, advance_step_tool\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "After K calibration variants are scored, advance_step_tool seeds K trajectories "
    "and flips loop_phase to 'review'. Re-dispatch the appropriate sub-agent for "
    "subsequent phases. Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_CALIBRATION_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='calibration') BEFORE spawning the sub-agent.\n\n"
    "PRE-DISPATCH CHECK: Before spawning, verify that "
    "outputs/{run_id}/search/build_dispatched.json does not exist. "
    "If it does, a build sub-agent is already in-flight — wait for it to complete.\n\n"
    "CALIBRATION MODE: No trajectories are seeded yet. The sub-agent must:\n"
    "  1. Activate odysseus_review_agent_cold_start to emit K diverse candidate prompts.\n"
    "  2. Call odysseus_prompt_builder to compile and register each candidate.\n"
    "  3. Call run_batch_eval to score all K candidates.\n"
    "  4. Call advance_step_tool to seed K trajectories from scored candidates and flip "
    "loop_phase to 'review'.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "odysseus_review_agent_cold_start, odysseus_prompt_builder, "
    "run_batch_eval, advance_step_tool\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "After K calibration variants are scored, advance_step_tool seeds K trajectories "
    "and flips loop_phase to 'review'. Re-dispatch the appropriate sub-agent for "
    "subsequent phases. Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

STAGE_4_CALIBRATION_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 4 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='calibration') BEFORE spawning the sub-agent.\n\n"
    "PRE-DISPATCH CHECK: Before spawning, verify that "
    "outputs/{run_id}/search/build_dispatched.json does not exist. "
    "If it does, a build sub-agent is already in-flight — wait for it to complete.\n\n"
    "CALIBRATION MODE: No trajectories are seeded yet. The sub-agent must:\n"
    "  1. Activate odysseus_review_agent_cold_start to emit K diverse candidate prompts.\n"
    "  2. Call odysseus_prompt_builder to compile and register each candidate.\n"
    "  3. Call run_batch_eval to score all K candidates.\n"
    "  4. Call advance_step_tool to seed K trajectories from scored candidates and flip "
    "loop_phase to 'review'.\n\n"
    "Sub-agent tools: get_pipeline_status, get_search_state_tool, "
    "odysseus_review_agent_cold_start, odysseus_prompt_builder, "
    "run_batch_eval, advance_step_tool\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "After K calibration variants are scored, advance_step_tool seeds K trajectories "
    "and flips loop_phase to 'review'. Re-dispatch the appropriate sub-agent for "
    "subsequent phases. Do not call stage tools yourself.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)

# ---------------------------------------------------------------------------
# Stage 5 — Final Report
# ---------------------------------------------------------------------------

STAGE_5_INSTRUCTION: str = (
    "<HARD_STOP>\n"
    "You MUST NOT call any Stage 5 tools from the current context.\n\n"
    "REQUIRED: Spawn a sub-agent with the <stage_system_prompt> below as its system prompt.\n\n"
    "PRE-DISPATCH: Call start_stage(run_id='{run_id}', stage='final_report') BEFORE spawning the sub-agent.\n\n"
    "Sub-agent tools: get_pipeline_status, filter_holdout_dataset_tool, "
    "list_pareto_candidates, run_holdout_eval, "
    "build_final_report_briefing_tool, save_final_report\n"
    "Your tools: get_pipeline_status only\n\n"
    "POST-EXIT: After the sub-agent returns, call complete_stage(run_id='{run_id}'), "
    "then call get_pipeline_status.\n"
    "If Stage 5 is not complete:\n"
    "  - Check the status detail field. If detail is 'version_selection_needed', read the\n"
    "    file at outputs/{run_id}/pareto_candidates_listed.json. Present the candidates\n"
    "    to the user as a table (version, quality score, cost, round) and ask which\n"
    "    prompt_version they want to evaluate on the holdout set.\n"
    "    You MUST wait for the user's actual reply. Do NOT assume, guess, or fabricate values.\n"
    "    Then call start_stage(run_id='{run_id}', stage='final_report') again to re-activate\n"
    "    the stage scope, and re-dispatch the sub-agent with the chosen prompt_version in the\n"
    "    conversation context. (Skipping start_stage will spawn the sub-agent with\n"
    "    orchestrator-scope tools and stage tools will be invisible.)\n"
    "  - Otherwise, call start_stage(run_id='{run_id}', stage='final_report') again, then\n"
    "    re-dispatch the sub-agent. Do not call stage tools yourself.\n"
    "  - If Stage 5 remains incomplete after 2 re-dispatches, report the error to the\n"
    "    user and halt.\n"
    "</HARD_STOP>\n\n"
    "<stage_system_prompt></stage_system_prompt>"
)
